"""Contracts: pydantic models and Protocols only. No logic, no I/O."""
from __future__ import annotations

from airport_agent.contracts.conversation import (
    Answer,
    ChatMessage,
    Citation,
    Intent,
    Plan,
    SessionState,
    Table,
    TableDisplay,
    ToolCallTrace,
)
from airport_agent.contracts.data_service import DataService
from airport_agent.contracts.llm import LLMClient, LLMError, LLMResult, ToolCall
from airport_agent.contracts.models import (
    HORIZONS,
    AirportFilter,
    AirportProfile,
    AirportRef,
    CuratedFact,
    Direction,
    FeatureMatrix,
    Horizon,
    HubSize,
    LiveStatus,
    Metric,
    MetricHorizon,
    MetricSpec,
    PeerGroup,
    Pillar,
    QualityFlag,
    RouteRow,
    RouteTable,
    SourceVintage,
    Tier,
)
from airport_agent.contracts.registry import (
    PILLAR_NAMES,
    default_registry_path,
    load_pillars,
    load_registry,
    registry_by_id,
)
from airport_agent.contracts.reports import (
    DeterministicReport,
    RankedItem,
    ScoreRow,
    SpecialistReport,
)
from airport_agent.contracts.requests import (
    MAX_HINT_CHARS,
    MAX_HINT_CHARS_GENERAL,
    AnalysisRequest,
    ExtendedOptions,
    QuestionType,
    SpecialistName,
    hint_limit,
    truncate_hint,
)
from airport_agent.contracts.scoring import DeterministicAnalyst
from airport_agent.contracts.specialists import SpecialistRunner
from airport_agent.contracts.tools import ToolSpec

__all__ = [
    "HORIZONS",
    "MAX_HINT_CHARS",
    "MAX_HINT_CHARS_GENERAL",
    "PILLAR_NAMES",
    "AirportFilter",
    "AirportProfile",
    "AirportRef",
    "AnalysisRequest",
    "Answer",
    "ChatMessage",
    "Citation",
    "CuratedFact",
    "DataService",
    "DeterministicAnalyst",
    "DeterministicReport",
    "Direction",
    "ExtendedOptions",
    "FeatureMatrix",
    "Horizon",
    "HubSize",
    "Intent",
    "LiveStatus",
    "LLMClient",
    "LLMError",
    "LLMResult",
    "Metric",
    "MetricHorizon",
    "MetricSpec",
    "PeerGroup",
    "Pillar",
    "Plan",
    "QualityFlag",
    "QuestionType",
    "RankedItem",
    "RouteRow",
    "RouteTable",
    "ScoreRow",
    "SessionState",
    "SourceVintage",
    "SpecialistName",
    "SpecialistReport",
    "SpecialistRunner",
    "Table",
    "TableDisplay",
    "Tier",
    "ToolCall",
    "ToolCallTrace",
    "ToolSpec",
    "default_registry_path",
    "hint_limit",
    "load_pillars",
    "load_registry",
    "registry_by_id",
    "truncate_hint",
]
